### PR TITLE
Branch fixing issues

### LINKED ISSUE #174: [PE-D] Done command help page not in line with actual command syntax
This is the command syntax for `done`, viewed by typing `help done`:

This is the bug observed when typing as per help page:

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: zhixiangteoh/ped#3

### LINKED ISSUE #179: [PE-D] UG typo in section `check`
Also, all arguments are indicated as optional `[ ]` but are not actually:

(Expected to just see all events, perhaps something similar to list, or maybe a warning message by program)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: zhixiangteoh/ped#8

### LINKED ISSUE #182: [PE-D] `delete` command does not work for specific EVENT_DATE, for "repeated" events
-------------
Labels: `severity.High` `type.FunctionalityBug`
original: zhixiangteoh/ped#11

### LINKED ISSUE #183: [PE-D] UG typo for `delete` command format, similar to `done`
As highlighted in yellow.

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: zhixiangteoh/ped#12

### LINKED ISSUE #203: [PE-D] [very low] typo in check command in UG
CS2113T-T12-4

should be end time

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: samuelchristopher/ped#3

### LINKED ISSUE #209: [PE-D] Done command did not prompt output
No details provided.

Set the first personal task to repeat weekly 5 times.
Typed command `done personal 1 30/10/20` but program did not prompt any output.

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: dozenmatter/ped#4

### PR DESCRIPTION
**Pull request by marcursor**
Let Qing Ning merge first if needed

Changed the table of contents to bulleted form, can see if it looks ok

### CODE REVIEW

**Comment by marcursor** [comment]
Closes #174, fixes #179, #182, #183, #203, #209

File: src/main/java/seedu/duke/command/DeleteCommand.java [hunk 1]
```diff
@@ -23,40 +24,60 @@ public DeleteCommand(String listType, String command) {
...
+     * Parses the user input and returns the corresponding DeleteCommand.
+     *
+     * @param input the processed user input with the command keyword removed.
+     * @return the DeleteCommand corresponding to the list type and event indicated in the input.
+     * @throws MissingSemicolonException if the input does not contain any semicolons to separate input fields.
+     * @throws WrongNumberOfArgumentsException if the event type or event index is missing.
+     * @throws WrongNumberFormatException if the event index is not an integer.
+     */
+    public static Command parse(String input) throws MissingSemicolonException, WrongNumberOfArgumentsException, WrongNumberFormatException {
+        if (!input.contains(";")) {
```
Comment (Colin386) [inline src/main/java/seedu/duke/command/DeleteCommand.java:38]: Nice. I think this is a good feature to add to remind users about the format to use

**Review by Colin386 — COMMENTED** [review]
Overall I think this is good. I like that there are reminders included to inform new users to use the standard semicolon to sepatate the command arguments
